version: '3'
services:
  postgres:
    container_name: pizza-db
    image: postgres:latest
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

networks:
  postgres:
    driver: bridge

volumes:
  data: